-- Catalog of medications per user
create table if not exists public.medications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  form text,
  strength text,
  notes text,
  active_from date not null,
  active_to date,
  created_at timestamptz not null default now(),
  check (active_to is null or active_to >= active_from)
);

create unique index if not exists medications_user_name_key
on public.medications (user_id, lower(name));

create index if not exists medications_user_active_idx
on public.medications (user_id, active_from, active_to);

alter table public.medications enable row level security;

drop policy if exists medications_select_own on public.medications;
create policy medications_select_own
on public.medications
for select
using (auth.uid() = user_id);

drop policy if exists medications_insert_own on public.medications;
create policy medications_insert_own
on public.medications
for insert
with check (auth.uid() = user_id);

drop policy if exists medications_update_own on public.medications;
create policy medications_update_own
on public.medications
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists medications_delete_own on public.medications;
create policy medications_delete_own
on public.medications
for delete
using (auth.uid() = user_id);

-- Versionable medication plans (scheduled/prn)
create table if not exists public.medication_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  medication_id bigint not null references public.medications(id) on delete cascade,
  type text not null check (type in ('scheduled', 'prn')),
  frequency text,
  time_window text check (time_window in ('morning', 'afternoon', 'night')),
  target_time time,
  tolerance_minutes integer,
  active_from date not null,
  active_to date,
  created_at timestamptz not null default now(),
  check (active_to is null or active_to >= active_from),
  check (tolerance_minutes is null or tolerance_minutes >= 0)
);

create index if not exists medication_plans_user_type_idx
on public.medication_plans (user_id, type, active_from, active_to);

create index if not exists medication_plans_medication_idx
on public.medication_plans (medication_id);

alter table public.medication_plans enable row level security;

drop policy if exists medication_plans_select_own on public.medication_plans;
create policy medication_plans_select_own
on public.medication_plans
for select
using (auth.uid() = user_id);

drop policy if exists medication_plans_insert_own on public.medication_plans;
create policy medication_plans_insert_own
on public.medication_plans
for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.medications m
    where m.id = medication_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists medication_plans_update_own on public.medication_plans;
create policy medication_plans_update_own
on public.medication_plans
for update
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.medications m
    where m.id = medication_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists medication_plans_delete_own on public.medication_plans;
create policy medication_plans_delete_own
on public.medication_plans
for delete
using (auth.uid() = user_id);

-- Real intake events
create table if not exists public.medication_intakes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  medication_id bigint not null references public.medications(id) on delete cascade,
  plan_id bigint references public.medication_plans(id) on delete set null,
  timestamp timestamptz not null,
  amount numeric(10, 3) not null default 1,
  source text not null check (source in ('scheduled', 'extra')),
  reason text check (reason in ('nervios', 'tics', 'presentacion', 'otro')),
  notes text,
  created_at timestamptz not null default now(),
  check (amount > 0)
);

create index if not exists medication_intakes_user_time_idx
on public.medication_intakes (user_id, timestamp desc);

create index if not exists medication_intakes_plan_idx
on public.medication_intakes (plan_id, timestamp desc);

create index if not exists medication_intakes_source_idx
on public.medication_intakes (user_id, source, timestamp desc);

alter table public.medication_intakes enable row level security;

drop policy if exists medication_intakes_select_own on public.medication_intakes;
create policy medication_intakes_select_own
on public.medication_intakes
for select
using (auth.uid() = user_id);

drop policy if exists medication_intakes_insert_own on public.medication_intakes;
create policy medication_intakes_insert_own
on public.medication_intakes
for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.medications m
    where m.id = medication_id
      and m.user_id = auth.uid()
  )
  and (
    plan_id is null
    or exists (
      select 1
      from public.medication_plans p
      where p.id = plan_id
        and p.user_id = auth.uid()
    )
  )
);

drop policy if exists medication_intakes_update_own on public.medication_intakes;
create policy medication_intakes_update_own
on public.medication_intakes
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists medication_intakes_delete_own on public.medication_intakes;
create policy medication_intakes_delete_own
on public.medication_intakes
for delete
using (auth.uid() = user_id);

-- Seed note:
-- The web app performs user-level first-run seed automatically:
-- Lorazepam + Atorvastatina medications, scheduled morning plans, and Lorazepam PRN plan.
