-- Weights per user
-- Optional for legacy single-user data:
-- select set_config('app.legacy_owner_user_id', '<AUTH_USER_UUID>', false);

create table if not exists public.weights (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ts timestamptz not null,
  weight numeric(10, 3) not null check (weight > 0),
  created_at timestamptz not null default now()
);

alter table public.weights add column if not exists user_id uuid;
alter table public.weights add column if not exists created_at timestamptz not null default now();

do $$
declare
  v_owner_user_id uuid;
  v_auth_user_count integer;
begin
  if exists (select 1 from public.weights where user_id is null) then
    begin
      v_owner_user_id := nullif(current_setting('app.legacy_owner_user_id', true), '')::uuid;
    exception
      when others then v_owner_user_id := null;
    end;

    if v_owner_user_id is null then
      select count(*)
      into v_auth_user_count
      from auth.users;

      if v_auth_user_count = 1 then
        select id
        into v_owner_user_id
        from auth.users
        order by created_at asc, id asc
        limit 1;
      else
        raise exception
          'public.weights contiene filas legacy sin user_id. Define app.legacy_owner_user_id antes de continuar.';
      end if;
    end if;

    update public.weights
    set user_id = v_owner_user_id
    where user_id is null;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'weights_user_id_fkey'
      and conrelid = 'public.weights'::regclass
  ) then
    alter table public.weights
      add constraint weights_user_id_fkey
      foreign key (user_id)
      references auth.users(id)
      on delete cascade;
  end if;
end
$$;

alter table public.weights alter column user_id set not null;

create index if not exists weights_user_ts_idx
on public.weights (user_id, ts desc);

alter table public.weights enable row level security;

drop policy if exists weights_select_own on public.weights;
create policy weights_select_own
on public.weights
for select
using (auth.uid() = user_id);

drop policy if exists weights_insert_own on public.weights;
create policy weights_insert_own
on public.weights
for insert
with check (auth.uid() = user_id);

drop policy if exists weights_update_own on public.weights;
create policy weights_update_own
on public.weights
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists weights_delete_own on public.weights;
create policy weights_delete_own
on public.weights
for delete
using (auth.uid() = user_id);
