-- Habits catalog per user
create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists habits_user_name_key
on public.habits (user_id, lower(name));

alter table public.habits enable row level security;

drop policy if exists habits_select_own on public.habits;
create policy habits_select_own
on public.habits
for select
using (auth.uid() = user_id);

drop policy if exists habits_insert_own on public.habits;
create policy habits_insert_own
on public.habits
for insert
with check (auth.uid() = user_id);

drop policy if exists habits_update_own on public.habits;
create policy habits_update_own
on public.habits
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists habits_delete_own on public.habits;
create policy habits_delete_own
on public.habits
for delete
using (auth.uid() = user_id);

-- Daily checks: one row per user + habit + date
create table if not exists public.habit_checks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint not null references public.habits(id) on delete cascade,
  log_date date not null,
  status smallint not null check (status in (0, 1)),
  created_at timestamptz not null default now(),
  unique (user_id, habit_id, log_date)
);

create index if not exists habit_checks_user_date_idx
on public.habit_checks (user_id, log_date);

alter table public.habit_checks enable row level security;

drop policy if exists habit_checks_select_own on public.habit_checks;
create policy habit_checks_select_own
on public.habit_checks
for select
using (auth.uid() = user_id);

drop policy if exists habit_checks_insert_own on public.habit_checks;
create policy habit_checks_insert_own
on public.habit_checks
for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.habits h
    where h.id = habit_id
      and h.user_id = auth.uid()
  )
);

drop policy if exists habit_checks_update_own on public.habit_checks;
create policy habit_checks_update_own
on public.habit_checks
for update
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.habits h
    where h.id = habit_id
      and h.user_id = auth.uid()
  )
);

drop policy if exists habit_checks_delete_own on public.habit_checks;
create policy habit_checks_delete_own
on public.habit_checks
for delete
using (auth.uid() = user_id);
